language: c
#######################################################################################
os:
  - linux
  
addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:
  - sudo apt-get update -qq
  
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 ~/toolchain/

#######################################################################################


script:  
  - export CROSS_COMPILE=~/toolchain/aarch64-linux-android-/bin
  - export KBUILD_BUILD_USER="yashpaljoshi"
  - export KBUILD_BUILD_HOST="Shivom"
  - make ARCH=arm64 l22_defconfig
  - make ARCH=arm64 Image.gz-dtb

after_success:
  - curl --upload-file arch/arm64/boot/Image.gz-dtb https://transfer.sh/mya_kernel
